modules:
  - name: prettier
    args:
      - --write
      - ./{src,test}/**/*.{js,ts}
  - name: eslint
    args:
      - ./{src,test}/**/*.{js,ts}
      - --fix
  - name: dependency-cruiser
    binary: depcruise
    args:
      - --config
      - .dependency-cruiser.js
      - src
      - -x
      - src/*.d.ts
  - name: jscpd
    args:
      - ./src
      - --blame
  - name: license-checker
    args:
      - --production
      - --json
      - --failOn='AGPL AGPL 1.0; AGPL 3.0; CDDL or GPLv2 with exceptions; CNRI
        Python GPL Compatible; Eclipse 1.0; Eclipse 2.0; GPL; GPL 1.0; GPL 2.0;
        GPL 2.0 Autoconf; GPL 2.0 Bison; GPL 2.0 Classpath; GPL 2.0 Font; GPL
        2.0 GCC; GPL 3.0; GPL 3.0 Autoconf; GPL 3.0 GCC; GPLv2 with XebiaLabs
        FLOSS License Exception; LGPL; LGPL 2.0; LGPL 2.1; LGPL 3.0; Suspected
        Eclipse 1.0; Suspected Eclipse 2.0'
  # TODO: need to sove token issue
  # - name: snyk
  #   args:
  #     - test
  #     - --severity-threshold=high
  - name: npm-audit
    moduleName: npm
    binary: npm
    args:
      - audit
ignoreMissingModules: true
