# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: [ubuntu-latest]
    name: Code Quality
    steps:
      - uses: actions/checkout@v2
      - name: Use nodejs@18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Init
        run: npm install --no-audit
      - name: Code Analysis
        run: npm run qa
        # TODO: haven't solved snynk yet
        # env:
        #   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  unit-tests:
    runs-on: [ubuntu-latest]
    name: Unit Tests
    steps:
      - uses: actions/checkout@v2
      - name: Use nodejs@18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Init
        run: npm install --no-audit
      - name: Code UnitTests
        run: npm run test
  build:
    name: Build and Deploy
    needs: [code-quality, unit-tests]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use nodejs@18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Init
        run: npm install --no-audit
      - name: Code Build
        run: npm run build
